---
title: "Core SNP benchmarking"
date: "2024-02-02"
author: "Ryan Wick"
output:
  html_document:
    pandoc_args: ["+RTS", "-K64m", "-RTS", "--self-contained",]
    df_print: paged
    keep_md: false
    toc: true
    toc_float: true
    code_folding: hide
---
```{r collapse=TRUE}
library(tidyverse)
library(knitr)
library(cowplot)
library(scales)

opts_chunk$set(dpi=300, fig.path='plots/', echo=TRUE, dev=c('png','pdf'), warning=FALSE, message=FALSE)
pdf.options(useDingbats = FALSE)
```


```{r load_data}
results <- read_delim("results.tsv", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
```

Ensure that the md5sum is the same for all unique combinations of test and genome_count.
```{r check_results}
check_integrity <- function(md5sums) {
  stopifnot(length(unique(md5sums)) == 1)
}

results %>%
  group_by(test, genome_count) %>%
  do({
    check_integrity(.$output_md5sum)
    . # Return the data unmodified if the assertion passes
  })
```

The 16-thread goalign didn't run any faster than the 1-thread, so drop 16-thread results:
```{r}
results <- results %>% filter(tool != "goalign 16 threads")
results$tool <- gsub("goalign 1 thread", "goalign", results$tool)
results$tool <- gsub("Core-SNP-Filter", "coresnpfilter", results$tool)
results$tool <- factor(results$tool, levels = c("goalign", "coresnpfilter", "snp-sites"))
```

Produce results dataframes with the best time/RAM for each tool:
```{r}
invariant_results <- results %>% filter(test == "invariant site removal") %>% select(genome_count, replicate, tool, seconds, ram_kb) %>%
  pivot_wider(names_from = replicate, values_from = c(seconds, ram_kb), names_sep = "_")
invariant_results$seconds <- apply(select(invariant_results, starts_with("seconds_")), 1, FUN = min, na.rm = TRUE)
invariant_results$ram_mb <- apply(select(invariant_results, starts_with("ram_kb_")), 1, FUN = min, na.rm = TRUE) / 1000.0

core_results <- results %>% filter(test == "95 core") %>% select(genome_count, replicate, tool, seconds, ram_kb) %>%
  pivot_wider(names_from = replicate, values_from = c(seconds, ram_kb), names_sep = "_")
core_results$seconds <- apply(select(core_results, starts_with("seconds_")), 1, FUN = min, na.rm = TRUE)
core_results$ram_mb <- apply(select(core_results, starts_with("ram_kb_")), 1, FUN = min, na.rm = TRUE) / 1000.0
```



```{r plot, fig.width = 10, fig.height = 6.5}
colours <- scale_color_manual(values = c("goalign" = "#1b9e77",
                                         "coresnpfilter" = "#d95f02",
                                         "snp-sites" = "#7570b3"))
shapes <- scale_shape_manual(values = c("goalign" = 15,
                                        "coresnpfilter" = 16,
                                        "snp-sites" = 17))

p1 <- ggplot(invariant_results, aes(x=genome_count, y=seconds, color=tool, shape=tool)) +
  geom_point(size=1.9) + geom_line(size=0.7) + colours + shapes +
  theme_bw() + theme(legend.position = "none") +
  scale_x_log10(labels = label_comma(), minor_breaks = NULL) +
  scale_y_log10(breaks = c(1, 10, 60, 600, 3600, 36000), minor_breaks = NULL,
                labels = c("1 s", "10 s", "1 m", "10 m", "1 h", "10 h"),
                limits = c(0.3, 36000)) +
  labs(title="Invariant removal time", x="genomes", y=NULL)

p2 <- ggplot(invariant_results, aes(x=genome_count, y=ram_mb, color=tool, shape=tool)) +
  geom_point(size=1.9) + geom_line(size=0.7) + colours + shapes +
  theme_bw() + theme(legend.position = "none") +
  scale_x_log10(labels = label_comma(), minor_breaks = NULL) +
  scale_y_log10(breaks = c(1, 10, 100, 1000, 10000, 100000), minor_breaks = NULL,
                labels = c("1 MB", "10 MB", "100 MB", "1 GB", "10 GB", "100 GB"),
                limits = c(10, 100000)) +
  labs(title="Invariant removal RAM usage", x="genomes", y=NULL)

p3 <- ggplot(core_results, aes(x=genome_count, y=seconds, color=tool, shape=tool)) +
  geom_point(size=1.9) + geom_line(size=0.7) + colours + shapes +
  theme_bw() + theme(legend.position = "none") +
  scale_x_log10(labels = label_comma(), minor_breaks = NULL) +
  # scale_y_log10(breaks = c(0.01, 0.1, 1, 10, 60, 600, 3600, 36000), minor_breaks = NULL,
                # labels = c("10 ms", "100 ms", "1 s", "10 s", "1 m", "10 m", "1 h", "10 h")) +
  scale_y_continuous(trans=scales::pseudo_log_trans(sigma = 0.004),
                     breaks = c(0.0, 0.01, 0.1, 1, 10, 60, 600, 3600, 36000), minor_breaks = NULL,
                     labels = c("<10 ms", "10 ms", "100 ms", "1 s", "10 s", "1 m", "10 m", "1 h", "10 h"),
                     limits = c(0.0, 63)) +
  labs(title="95% core time", x="genomes", y=NULL)

p4 <- ggplot(core_results, aes(x=genome_count, y=ram_mb, color=tool, shape=tool)) +
  geom_point(size=1.9) + geom_line(size=0.7) + colours + shapes +
  theme_bw() + theme(legend.position = "none") +
  scale_x_log10(labels = label_comma(), minor_breaks = NULL) +
  scale_y_log10(breaks = c(1, 10, 100, 1000, 10000, 100000), minor_breaks = NULL,
                labels = c("1 MB", "10 MB", "100 MB", "1 GB", "10 GB", "100 GB"),
                limits = c(1, 10000)) +
  labs(title="95% core RAM usage", x="genomes", y=NULL)

legend <- get_legend(p1 + theme(legend.position = "right", legend.title=element_blank()))

plot_grid(plot_grid(p1, p2, p3, p4, nrow = 2, align = 'hv'), legend, nrow=1, rel_widths=c(1, 0.2))
```